import type {
  AssessmentQuestion,
  Competency,
  Course,
  LearnerProfile,
} from "./types";

export const DEMO_PROFILE: LearnerProfile = {
  name: "Ananya Sharma",
  designation: "Statistical Officer",
  division: "Official Statistics Division",
  department: "Ministry of Statistics & Programme Implementation",
  grade: "Group B (Gazetted)",
  location: "New Delhi",
  email: "employee@demo.gov.in",
  joinedOn: "2019-07-15",
  learningHours: 46,
};

export const COMPETENCIES: Competency[] = [
  // Statistical
  { id: "survey-design", name: "Survey Design", category: "Statistical", required: 5, description: "Designing household and enterprise surveys, questionnaire construction and pilot testing." },
  { id: "sampling", name: "Sampling Techniques", category: "Statistical", required: 5, description: "Probability sampling, stratification, multi-stage designs and weight estimation." },
  { id: "national-accounts", name: "National Accounts", category: "Statistical", required: 4, description: "GDP compilation, SNA 2008 concepts, supply-use tables." },
  { id: "price-statistics", name: "Price Statistics", category: "Statistical", required: 4, description: "CPI/WPI construction, index number theory and base revision." },
  { id: "data-quality", name: "Data Quality Assurance", category: "Statistical", required: 5, description: "Editing, imputation, non-sampling error control and quality frameworks." },
  { id: "econometrics", name: "Econometrics & Forecasting", category: "Statistical", required: 3, description: "Regression, time-series modelling and seasonal adjustment." },
  { id: "official-stats-standards", name: "Official Statistics Standards", category: "Statistical", required: 4, description: "UN Fundamental Principles, NQAF and classification standards." },
  // Technical
  { id: "python", name: "Python for Data Analysis", category: "Technical", required: 4, description: "pandas, numpy and reproducible analysis pipelines." },
  { id: "r-stats", name: "R for Statistical Computing", category: "Technical", required: 3, description: "R programming, survey package and reporting with R Markdown." },
  { id: "sql", name: "SQL & Data Management", category: "Technical", required: 4, description: "Relational modelling, joins, aggregation and query optimisation." },
  { id: "ai-ml", name: "AI / Machine Learning", category: "Technical", required: 4, description: "Supervised learning, model validation and responsible AI in official statistics." },
  { id: "gis", name: "GIS & Geospatial Analysis", category: "Technical", required: 3, description: "Spatial data handling, geo-coding and thematic mapping." },
  { id: "big-data", name: "Big Data & Alternative Sources", category: "Technical", required: 3, description: "Administrative data, web-scraped data and scalable processing." },
  { id: "data-viz", name: "Data Visualisation", category: "Technical", required: 4, description: "Dashboards, statistical graphics and dissemination products." },
  // Digital Governance
  { id: "cybersecurity", name: "Cyber Security & Data Protection", category: "Digital Governance", required: 4, description: "Information security, DPDP Act obligations and confidentiality." },
  { id: "e-governance", name: "e-Governance & Digital Public Infrastructure", category: "Digital Governance", required: 3, description: "DPI building blocks, API-based service delivery and interoperability." },
  { id: "open-data", name: "Open Data & Dissemination", category: "Digital Governance", required: 3, description: "NDSAP compliance, metadata standards and machine-readable release." },
  // Behavioural & Managerial
  { id: "communication", name: "Statistical Communication", category: "Behavioural & Managerial", required: 4, description: "Explaining statistics to policy makers, media and citizens." },
  { id: "project-management", name: "Project & Field Management", category: "Behavioural & Managerial", required: 3, description: "Planning survey rounds, field supervision and resource allocation." },
  { id: "leadership", name: "Leadership & Collaboration", category: "Behavioural & Managerial", required: 3, description: "Team building, mentoring and inter-departmental coordination." },
];

export const competencyById = (id: string) =>
  COMPETENCIES.find((c) => c.id === id);

/** Baseline levels before the officer takes the competency assessment. */
export const BASELINE_LEVELS: Record<string, number> = {
  "survey-design": 3,
  sampling: 3,
  "national-accounts": 2,
  "price-statistics": 3,
  "data-quality": 3,
  econometrics: 2,
  "official-stats-standards": 3,
  python: 2,
  "r-stats": 2,
  sql: 2,
  "ai-ml": 1,
  gis: 1,
  "big-data": 2,
  "data-viz": 3,
  cybersecurity: 2,
  "e-governance": 2,
  "open-data": 3,
  communication: 3,
  "project-management": 3,
  leadership: 2,
};

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: "q1",
    competencyId: "sampling",
    prompt: "In a stratified random sample, proportional allocation assigns sample size to each stratum in proportion to:",
    options: ["Stratum variance only", "Stratum population size", "The inverse of the stratum mean", "Survey cost per unit"],
    correctIndex: 1,
    explanation: "Proportional allocation distributes the sample in proportion to stratum size (N_h / N).",
  },
  {
    id: "q2",
    competencyId: "sampling",
    prompt: "A design effect (DEFF) of 2.0 for a cluster sample implies:",
    options: ["The sample is twice as precise as an SRS", "Variance is twice that of an SRS of the same size", "Half the sample is non-response", "Clusters were selected with equal probability"],
    correctIndex: 1,
    explanation: "DEFF is the ratio of the design variance to the SRS variance; 2.0 means variance is doubled.",
  },
  {
    id: "q3",
    competencyId: "survey-design",
    prompt: "The main purpose of a pilot survey before a national round is to:",
    options: ["Publish preliminary national estimates", "Test instruments, field procedures and timings", "Replace the sampling frame", "Reduce the required sample size"],
    correctIndex: 1,
    explanation: "Pilots validate questionnaires, instructions, field logistics and expected response burden.",
  },
  {
    id: "q4",
    competencyId: "survey-design",
    prompt: "Which question wording issue creates a 'double-barrelled' question?",
    options: ["Using a filter question", "Asking about two distinct issues in one question", "Offering a 'Don't know' option", "Using a 5-point scale"],
    correctIndex: 1,
    explanation: "A double-barrelled question asks about two things at once, so the answer is ambiguous.",
  },
  {
    id: "q5",
    competencyId: "data-quality",
    prompt: "Non-sampling error in an official survey is best reduced by:",
    options: ["Increasing the sample size", "Improved training, editing and follow-up of non-response", "Using a larger confidence level", "Switching to systematic sampling"],
    correctIndex: 1,
    explanation: "Non-sampling error is unrelated to sample size; process quality controls address it.",
  },
  {
    id: "q6",
    competencyId: "data-quality",
    prompt: "Hot-deck imputation replaces a missing value with:",
    options: ["The overall mean", "A value from a similar responding unit", "Zero", "A regression prediction with noise removed"],
    correctIndex: 1,
    explanation: "Hot-deck donates a value from a similar (donor) record in the same dataset.",
  },
  {
    id: "q7",
    competencyId: "python",
    prompt: "In pandas, df.groupby('state')['income'].transform('mean') returns:",
    options: ["One row per state", "A Series aligned to the original rows", "A pivot table", "A NumPy scalar"],
    correctIndex: 1,
    explanation: "transform broadcasts the group statistic back to the original index shape.",
  },
  {
    id: "q8",
    competencyId: "python",
    prompt: "Which is the most reproducible way to fix randomness in a Python analysis pipeline?",
    options: ["Run the script twice", "Set an explicit random seed / Generator", "Sort the data", "Use float32 instead of float64"],
    correctIndex: 1,
    explanation: "Explicit seeding (e.g. numpy default_rng(seed)) makes runs reproducible.",
  },
  {
    id: "q9",
    competencyId: "sql",
    prompt: "Which SQL clause filters rows AFTER aggregation?",
    options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
    correctIndex: 1,
    explanation: "HAVING applies conditions to aggregated groups; WHERE filters before aggregation.",
  },
  {
    id: "q10",
    competencyId: "sql",
    prompt: "A LEFT JOIN between survey_household and survey_member returns:",
    options: ["Only matched households", "All households, with NULLs where no member matches", "Only unmatched rows", "The Cartesian product"],
    correctIndex: 1,
    explanation: "A LEFT JOIN preserves all left-table rows regardless of a match.",
  },
  {
    id: "q11",
    competencyId: "gis",
    prompt: "Reprojecting a village boundary layer is required when:",
    options: ["The attribute table has missing values", "Layers use different coordinate reference systems", "The file is a shapefile", "The map has no legend"],
    correctIndex: 1,
    explanation: "Spatial overlay needs a common CRS; otherwise geometries will not align.",
  },
  {
    id: "q12",
    competencyId: "ai-ml",
    prompt: "A classification model shows 98% training accuracy but 61% on held-out data. This indicates:",
    options: ["Underfitting", "Overfitting", "Class balance", "Label leakage is impossible"],
    correctIndex: 1,
    explanation: "A large train-test gap is the classic signature of overfitting.",
  },
  {
    id: "q13",
    competencyId: "ai-ml",
    prompt: "Before using a machine-learning model to impute official statistics, the most important safeguard is:",
    options: ["Maximising model complexity", "Documented validation against known outcomes and bias checks", "Using the newest library version", "Hiding the methodology"],
    correctIndex: 1,
    explanation: "Official statistics require transparent, validated and bias-checked methods.",
  },
  {
    id: "q14",
    competencyId: "cybersecurity",
    prompt: "Unit-level survey records shared with a researcher should first be:",
    options: ["Published on the open data portal", "De-identified and released under a controlled agreement", "Emailed as a spreadsheet", "Compressed with a password in the same email"],
    correctIndex: 1,
    explanation: "Statistical confidentiality requires de-identification plus controlled access.",
  },
  {
    id: "q15",
    competencyId: "cybersecurity",
    prompt: "Multi-factor authentication primarily protects against:",
    options: ["Disk failure", "Compromised passwords", "Slow networks", "Data entry typos"],
    correctIndex: 1,
    explanation: "MFA adds a second factor so a stolen password alone is not enough.",
  },
];

export const IGOT_COURSES: Course[] = [
  { id: "igot-101", code: "MoSPI/SAM/101", title: "Advanced Sampling Methods for Large-Scale Surveys", provider: "iGOT Karmayogi · NSSTA", competencyIds: ["sampling", "survey-design"], level: 4, durationHours: 18, format: "Blended", rating: 4.7, learners: 4820, departmentPriority: 0.95, careerRelevance: 0.9, roleRelevance: 0.95, description: "Multi-stage designs, weighting, variance estimation and practical field constraints for national rounds." },
  { id: "igot-102", code: "MoSPI/SUR/118", title: "Questionnaire Design and Cognitive Testing", provider: "iGOT Karmayogi · NSSTA", competencyIds: ["survey-design", "data-quality"], level: 3, durationHours: 12, format: "Self-paced", rating: 4.5, learners: 3310, departmentPriority: 0.8, careerRelevance: 0.75, roleRelevance: 0.9, description: "Build instruments that minimise measurement error, with cognitive interviewing practice." },
  { id: "igot-103", code: "MoSPI/PY/210", title: "Python for Official Statistics", provider: "iGOT Karmayogi · NIC Academy", competencyIds: ["python", "data-viz"], level: 4, durationHours: 24, format: "Self-paced", rating: 4.8, learners: 9120, departmentPriority: 0.9, careerRelevance: 0.95, roleRelevance: 0.85, description: "pandas-based cleaning, tabulation and reproducible statistical production pipelines." },
  { id: "igot-104", code: "MoSPI/SQL/205", title: "SQL and Data Management for Statistical Systems", provider: "iGOT Karmayogi · NIC Academy", competencyIds: ["sql", "big-data"], level: 3, durationHours: 16, format: "Self-paced", rating: 4.6, learners: 7640, departmentPriority: 0.85, careerRelevance: 0.85, roleRelevance: 0.8, description: "Relational modelling of survey data, complex joins, window functions and performance." },
  { id: "igot-105", code: "MoSPI/AI/301", title: "Applied Machine Learning for Public Data", provider: "iGOT Karmayogi · IIM Skill Hub", competencyIds: ["ai-ml", "python"], level: 4, durationHours: 30, format: "Instructor-led", rating: 4.6, learners: 2870, departmentPriority: 1.0, careerRelevance: 0.95, roleRelevance: 0.8, description: "Model selection, validation, fairness and documentation for AI use in official statistics." },
  { id: "igot-106", code: "MoSPI/GIS/150", title: "Geospatial Analysis for Survey Operations", provider: "iGOT Karmayogi · ISRO-IIRS", competencyIds: ["gis"], level: 3, durationHours: 20, format: "Blended", rating: 4.4, learners: 1980, departmentPriority: 0.8, careerRelevance: 0.7, roleRelevance: 0.7, description: "Geo-coding of enumeration blocks, spatial joins and thematic map production." },
  { id: "igot-107", code: "MoSPI/SEC/140", title: "Cyber Security and Data Protection in Government", provider: "iGOT Karmayogi · CERT-In", competencyIds: ["cybersecurity", "e-governance"], level: 3, durationHours: 10, format: "Self-paced", rating: 4.3, learners: 12400, departmentPriority: 0.9, careerRelevance: 0.7, roleRelevance: 0.75, description: "DPDP Act duties, statistical confidentiality and secure handling of unit-level data." },
  { id: "igot-108", code: "MoSPI/NAS/220", title: "National Accounts Statistics: Concepts and Compilation", provider: "iGOT Karmayogi · NSSTA", competencyIds: ["national-accounts"], level: 4, durationHours: 22, format: "Instructor-led", rating: 4.5, learners: 1620, departmentPriority: 0.75, careerRelevance: 0.8, roleRelevance: 0.7, description: "SNA 2008 framework, supply-use tables and GDP estimation in the Indian context." },
  { id: "igot-109", code: "MoSPI/CPI/160", title: "Price Index Compilation and Base Revision", provider: "iGOT Karmayogi · NSSTA", competencyIds: ["price-statistics"], level: 3, durationHours: 14, format: "Self-paced", rating: 4.2, learners: 2110, departmentPriority: 0.6, careerRelevance: 0.65, roleRelevance: 0.65, description: "Index number theory, weight updating and quality adjustment in CPI/WPI." },
  { id: "igot-110", code: "MoSPI/DQ/175", title: "Data Quality Frameworks and Statistical Editing", provider: "iGOT Karmayogi · NSSTA", competencyIds: ["data-quality", "official-stats-standards"], level: 4, durationHours: 15, format: "Blended", rating: 4.6, learners: 3550, departmentPriority: 0.9, careerRelevance: 0.8, roleRelevance: 0.9, description: "NQAF-aligned quality assurance, selective editing and imputation strategies." },
  { id: "igot-111", code: "MoSPI/VIZ/130", title: "Dashboards and Statistical Dissemination", provider: "iGOT Karmayogi · NIC Academy", competencyIds: ["data-viz", "open-data"], level: 3, durationHours: 12, format: "Self-paced", rating: 4.4, learners: 5230, departmentPriority: 0.7, careerRelevance: 0.75, roleRelevance: 0.8, description: "Design principles for statistical graphics, dashboards and machine-readable releases." },
  { id: "igot-112", code: "MoSPI/R/190", title: "R and the survey Package", provider: "iGOT Karmayogi · ISI Extension", competencyIds: ["r-stats", "sampling"], level: 3, durationHours: 18, format: "Self-paced", rating: 4.3, learners: 2440, departmentPriority: 0.65, careerRelevance: 0.7, roleRelevance: 0.7, description: "Complex survey analysis in R with correct variance estimation." },
  { id: "igot-113", code: "MoSPI/BD/230", title: "Administrative and Big Data for Statistics", provider: "iGOT Karmayogi · NSSTA", competencyIds: ["big-data", "e-governance"], level: 4, durationHours: 20, format: "Blended", rating: 4.5, learners: 1740, departmentPriority: 0.85, careerRelevance: 0.85, roleRelevance: 0.7, description: "Integrating administrative registers and alternative data into official outputs." },
  { id: "igot-114", code: "MoSPI/COM/120", title: "Communicating Statistics to Policy Makers", provider: "iGOT Karmayogi · LBSNAA", competencyIds: ["communication", "leadership"], level: 3, durationHours: 8, format: "Self-paced", rating: 4.5, learners: 6890, departmentPriority: 0.6, careerRelevance: 0.8, roleRelevance: 0.75, description: "Narrative, uncertainty communication and briefing note craft." },
  { id: "igot-115", code: "MoSPI/PM/145", title: "Field Operations and Survey Project Management", provider: "iGOT Karmayogi · NSSTA", competencyIds: ["project-management", "leadership"], level: 3, durationHours: 14, format: "Blended", rating: 4.2, learners: 2960, departmentPriority: 0.7, careerRelevance: 0.7, roleRelevance: 0.7, description: "Round planning, supervision protocols and resource management for field work." },
  { id: "igot-116", code: "MoSPI/ECO/240", title: "Time Series Analysis and Seasonal Adjustment", provider: "iGOT Karmayogi · ISI Extension", competencyIds: ["econometrics"], level: 4, durationHours: 20, format: "Instructor-led", rating: 4.4, learners: 1380, departmentPriority: 0.6, careerRelevance: 0.75, roleRelevance: 0.6, description: "ARIMA, X-13 seasonal adjustment and nowcasting for economic indicators." },
];

export const DEPARTMENTS = [
  "All Departments",
  "Official Statistics Division",
  "National Accounts Division",
  "Price Statistics Division",
  "Field Operations Division",
  "Data Informatics & Innovation",
  "State Directorates of Economics & Statistics",
];
