/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as CompetenciesRouteImport } from './routes/competencies'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as LearningPathRouteImport } from './routes/learning-path'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McqRouteImport } from './routes/mcq'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciesRoute = CompetenciesRouteImport.update({
  id: '/competencies',
  path: '/competencies',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathRoute = LearningPathRouteImport.update({
  id: '/learning-path',
  path: '/learning-path',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McqRoute = McqRouteImport.update({
  id: '/mcq',
  path: '/mcq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/competencies': typeof CompetenciesRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/gaps': typeof GapsRoute
  '/learning-path': typeof LearningPathRoute
  '/login': typeof LoginRoute
  '/mcq': typeof McqRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/competencies': typeof CompetenciesRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/gaps': typeof GapsRoute
  '/learning-path': typeof LearningPathRoute
  '/login': typeof LoginRoute
  '/mcq': typeof McqRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/competencies': typeof CompetenciesRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/gaps': typeof GapsRoute
  '/learning-path': typeof LearningPathRoute
  '/login': typeof LoginRoute
  '/mcq': typeof McqRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assessment'
    | '/competencies'
    | '/courses'
    | '/dashboard'
    | '/gaps'
    | '/learning-path'
    | '/login'
    | '/mcq'
    | '/profile'
    | '/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assessment'
    | '/competencies'
    | '/courses'
    | '/dashboard'
    | '/gaps'
    | '/learning-path'
    | '/login'
    | '/mcq'
    | '/profile'
    | '/progress'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assessment'
    | '/competencies'
    | '/courses'
    | '/dashboard'
    | '/gaps'
    | '/learning-path'
    | '/login'
    | '/mcq'
    | '/profile'
    | '/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssessmentRoute: typeof AssessmentRoute
  CompetenciesRoute: typeof CompetenciesRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  GapsRoute: typeof GapsRoute
  LearningPathRoute: typeof LearningPathRoute
  LoginRoute: typeof LoginRoute
  McqRoute: typeof McqRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies': {
      id: '/competencies'
      path: '/competencies'
      fullPath: '/competencies'
      preLoaderRoute: typeof CompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-path': {
      id: '/learning-path'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof LearningPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq': {
      id: '/mcq'
      path: '/mcq'
      fullPath: '/mcq'
      preLoaderRoute: typeof McqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssessmentRoute: AssessmentRoute,
  CompetenciesRoute: CompetenciesRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  GapsRoute: GapsRoute,
  LearningPathRoute: LearningPathRoute,
  LoginRoute: LoginRoute,
  McqRoute: McqRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
